let links = [
    // Humanoid
    { id: 1, title: "Boston Dynamics<br>(Dynamic Mobility & Industrial Autonomy)", category: "humanoid", source: "Boston Dynamics", url: "https://www.bostondynamics.com/", country: "us" }, 
    { id: 6, title: "Engineered Arts<br>(Social AI Humanoid & Lifelike Expressions)", category: "humanoid", source: "Engineered Arts", url: "https://www.engineeredarts.co.uk/", country: "gb" },
    { id: 104, title: "XPENG Robotics (IRON)", category: "humanoid", source: "XPENG", url: "https://www.xpeng.com", country: "cn" }, 
    { id: 1012, title: "Figure AI<br>(General-Purpose Humanoid & Helix AI)", category: "humanoid", source: "Figure", url: "https://www.figure.ai/", country: "us" },
    { id: 1013, title: "Apptronik<br>(General-Purpose Industrial Humanoid)", category: "humanoid", source: "Apptronik", url: "https://apptronik.com/", country: "us" },
    { id: 1014, title: "Agility Robotics<br>(Logistics Humanoid)", category: "humanoid", source: "Agility Robotics", url: "https://www.agilityrobotics.com/", country: "us" },
    { id: 1015, title: "1X Technologies<br>(AI-powered Home Humanoid)", category: "humanoid", source: "1X", url: "https://www.1x.tech/neo/", country: "no" },
    { id: 1017, title: "Rainbow Robotics<br>(Multipurpose Humanoid & Cobot Platform)", category: "humanoid", source: "Rainbow", url: "http://www.rainbow-robotics.com/", country: "kr" },
    { id: 1012, title: "Unitree Robotics<br>(Mass-Market Humanoid & High-Speed Quadruped)", category: "humanoid", source: "Leader in Affordable High-Performance Robotics", url: "https://www.unitree.com/", country: "cn" },
    { id: 1019, title: "UBTECH<br>(Industrial & Service Humanoid)", category: "humanoid", source: "UBTECH", url: "https://www.ubtrobot.com/", country: "cn" },
    { id: 1020, title: "Xiaomi<br>(Emotion-Sensing Humanoid)", category: "humanoid", source: "Xiaomi", url: "https://www.mi.com/global/discover/article?id=2754", country: "cn" },
    { id: 1023, title: "PAL Robotics<br>(Industrial-Grade Torque Controlled Humanoid)", category: "humanoid", source: "PAL Robotics", url: "https://pal-robotics.com/robots/talos/", country: "es" },
    { id: 1025, title: "Sanctuary AI<br>(General-Purpose Humanoid & Dexterous Hand)", category: "humanoid", source: "Sanctuary AI", url: "https://www.sanctuary.ai/", country: "ca" },
    { id: 1026, title: "Meka Robotics (Google DeepMind)", category: "humanoid", source: "Research", url: "https://deepmind.google/discover/blog/", country: "us" },
    { id: 1027, title: "IIT (iCub)<br>(Open Source Research Humanoid)", category: "humanoid", source: "Research", url: "https://icub.iit.it/", country: "it" },
    { id: 1029, title: "NEURA Robotics<br>(Cognitive Humanoid & Smart Cobots)", category: "humanoid", source: "Europe's Pioneer in Cognitive Robotics", url: "https://neura-robotics.com/", country: "de" },
    { id: 1060, title: "Agibot<br>(Universal Humanoid)", category: "humanoid", source: "Embodied AI Pioneer", url: "https://www.agibot.com/", country: "cn" },
    { id: 1130, title: "AeiROBOT<br>(General-Purpose Humanoid Platform)", category: "humanoid", source: "Humanoid Robot Platform", url: "https://eng.arobot4all.com/", country: "kr" },
    { id: 1210, title: "Sharpa Robotics<br>(dexterous robotic hand)", category: "humanoid", source: "Dexterous Robotic Hand (SharpaWave)", url: "https://www.sharpa.com/", country: "sg" },
    { id: 106, title: "Fourier Robotics<br>(General-Purpose Humanoid)", category: "humanoid", source: "Embodied AI & Rehab Origin", url: "https://www.fftai.com/", country: "cn" },

    // Industrial
    { id: 201, title: "FANUC Robotics<br>(Global Industrial Infrastructure)", category: "Industrial", source: "FANUC", url: "https://www.fanuc.co.jp/eindex.html", country: "jp" }, 
    { id: 202, title: "ABB Robotics<br>(Industrial & Collaborative Solutions)", category: "Industrial", source: "ABB", url: "https://new.abb.com/products/robotics", country: "ch" }, 
    { id: 2, title: "KUKA Industrial Robots", category: "Industrial", source: "KUKA", url: "https://www.kuka.com/", country: "de" }, 
    { id: 204, title: "YASKAWA Robotics", category: "Industrial", source: "YASKAWA", url: "https://www.yaskawa.co.jp/en/products/robotics", country: "jp" },
    { id: 205, title: "SIASUN Robotics", category: "Industrial", source: "SIASUN", url: "http://www.siasun.com/", country: "cn" }, 
    { id: 206, title: "Estun Automation<br>(Motion Control & Industrial Robotics)", category: "Industrial", source: "Estun", url: "https://www.estun.com/", country: "cn" },
    { id: 207, title: "Doosan Robotics<br>(Collaborative & AI Robot Solutions)", category: "Industrial", sub: "Collaborative Robots", url: "https://www.doosanrobotics.com/kr/", country: "kr" },
    { id: 208, title: "Neuromeka (Indy)", category: "Industrial", sub: "Collaborative Robots", url: "https://www.neuromeka.com/", country: "kr" },
    { id: 1101, title: "Universal Robots", category: "Industrial", sub: "Collaborative Robots", url: "https://www.universal-robots.com/", country: "dk" },
    { id: 1108, title: "FBR<br>(Autonomous Construction & Robotic Bricklaying)", category: "Industrial", sub: "Construction Robotics", url: "https://www.fbr.com.au/", country: "au" },
    { id: 210, title: "Epson Robots<br>(High-Speed Precision SCARA & 6-Axis)", category: "Industrial", source: "SCARA Leader", url: "https://epson.com/robots", country: "jp" },
    { id: 211, title: "Kawasaki Robotics", category: "Industrial", source: "Industrial Giants", url: "https://kawasakirobotics.com/", country: "jp" },
    { id: 212, title: "DENSO Robotics<br>(High-Precision Small Assembly & Collaborative Robot)", category: "Industrial", source: "Small Assembly", url: "https://www.denso-robotics.com/", country: "jp" },
    { id: 213, title: "Techman Robot", category: "Industrial", source: "AI Cobot", url: "https://www.tm-robot.com/en/", country: "tw" },
    { id: 220, title: "Standard Bots (AI-native Cobots)", category: "Industrial", source: "Low-cost AI Robots", url: "https://standardbots.com/", country: "us" },
    { id: 221, title: "Rockwell Automation", category: "Industrial", source: "Digital Transformation", url: "https://www.rockwellautomation.com/", country: "us" },
    { id: 1102, title: "Robotnik (A URG Company)", category: "Industrial", source: "Mobile & Industrial Robots", url: "https://robotnik.eu/", country: "es" },
    { id: 215, title: "NAU Robotics<br>(Smart Industrial & Logistics)", category: "Industrial", source: "Leading K-Robot Automation Solutions", url: "https://www.naurobot.com/", country: "kr" },
    { id: 230, title: "OMRON Robotics<br>(Industrial & Collaborative)", category: "Industrial", source: "Integrated Automation & AI", url: "https://robotics.omron.com/", country: "jp" },
    { id: 231, title: "Stäubli Robotics<br>(High-Precision & Cleanroom)", category: "Industrial", source: "Swiss Precision Robotics", url: "https://www.staubli.com/en-us/robotics/", country: "ch" },
    { id: 232, title: "Comau<br>(Stellantis Automation)", category: "Industrial", source: "Automotive & Industrial Arms", url: "https://www.comau.com/en/", country: "it" },
    { id: 1451, title: "ANYbotics<br>(ANYmal - Industrial Inspection)", category: "Home & BLDG", source: "Autonomous Legged Inspection Robot", url: "https://www.anybotics.com/", country: "ch" },

    // Service
    { id: 401, title: "SoftBank Robotics", category: "service", source: "SoftBank", url: "https://www.softbankrobotics.com/", country: "jp" }, 
    { id: 402, title: "Bear Robotics (Serving)", category: "service", source: "Bear Robotics", url: "https://www.bearrobotics.com/", country: "us" }, 
    { id: 4, title: "Aethon Mobile Robots", category: "service", source: "Aethon", url: "https://www.aethon.com/", country: "us" }, 
    { id: 403, title: "Pudu Robotics (Serving Robots)", category: "service", source: "Pudu", url: "https://www.pudurobotics.com/", country: "cn" },
    { id: 404, title: "KEENON Robotics (Serving, Delivery)", category: "service", source: "KEENON", url: "https://www.keenon.com/", country: "cn" }, 
    { id: 405, title: "LG CLOi ServeBot (Serving, Guide)", category: "service", source: "LG Electronics", url: "https://www.lg.com/global/business/robot/servebot", country: "kr" }, 
    { id: 406, title: "KT AI Robot (Serving, Delivery)", category: "service", source: "KT", url: "https://ktrobotech.com/", country: "kr" }, 
    { id: 407, title: "Woowa Brothers (Baemin Dilly)", category: "service", source: "Woowa Brothers", url: "https://robot.baemin.com/", country: "kr" }, 
    { id: 408, title: "Robotis (Delivery Robot 'Gaemi')", category: "service", source: "Robotis", url: "https://www.robotis.com/sub/business_012.php", country: "kr" }, 
    { id: 409, title: "Neubility<br>(Delivery & Patrol Robot)", category: "service", source: "Neubility", url: "https://www.neubility.co.kr/ir", country: "kr" }, 
    { id: 410, title: "XYZ (Barista, Delivery)", category: "service", source: "XYZ", url: "https://xyzcorp.io/", country: "kr" }, 
    { id: 411, title: "EOS Korea (Serving Robot)", category: "service", source: "EOS Korea", url: "https://eoskorea.kr/category/%EC%9D%B4%EC%98%A4%EC%8A%A4-%EC%84%9C%EB%B9%99%EB%A1%9C%EB%B4%87/43/", country: "kr" }, 
    { id: 412, title: "Segway Robotics (Delivery & Mobility)", category: "service", source: "Segway-Ninebot", url: "https://robotics.segway.com/", country: "cn" },
    { id: 413, title: "Gausium (Cleaning Robots)", category: "service", source: "Gausium", url: "https://www.gausium.com/", country: "cn" },
    { id: 414, title: "Excelland (Hotel & Delivery Robots)", category: "service", source: "Excelland", url: "https://www.excelland.com/en/", country: "cn" },
    { id: 415, title: "YOGO Robot (Multi-robot Dispatch)", category: "service", source: "YOGO Robot", url: "https://www.yogorobot.com/", country: "cn" },
    { id: 416, title: "Candela (Delivery & Sanitation)", category: "service", source: "Candela", url: "https://www.candelarobot.com/en/", country: "cn" },
    { id: 417, title: "Reeman Robotics (Platform & Service)", category: "service", source: "Reeman", url: "https://www.reemanrobot.com/", country: "cn" },
    { id: 1104, title: "Rosenbauer Robotics", category: "service", sub: "Firefighting Robots", url: "https://www.rosenbauer.com/", country: "at" },
    { id: 450, title: "Diligent Robotics (Moxi)", category: "service", source: "Hospital Service Robot", url: "https://www.diligentrobots.com/", country: "us" },
    { id: 1100, title: "United Robotics Group (URG)", category: "service", source: "Service Robotics Ecosystem", url: "https://unitedrobotics.group/en-us", country: "de" },{ id: 4006, title: "Diligent Robotics<br>(Moxi - Hospital Support Robot)", category: "Service", source: "Nurse Assistant with Manipulator Arm", url: "https://diligentrobots.com/", country: "us" },
           
    // Mobility 
    { id: 501, title: "Waymo<br>(Ride-hailing service)", category: "mobility", source: "Alphabet", url: "https://waymo.com/", country: "us" },
    { id: 502, title: "Tesla<br>(FSD/Robotaxi)", category: "mobility", source: "Tesla Inc.", url: "https://www.tesla.com/AI", country: "us" },
    { id: 503, title: "Cruise<br>(Driverless Ride)", category: "mobility", source: "GM Subsidiary", url: "https://www.getcruise.com/", country: "us" },
    { id: 504, title: "Zoox<br>(Amazon Mobility)", category: "mobility", source: "Amazon", url: "https://www.zoox.com/", country: "us" },
    { id: 505, title: "Baidu Apollo<br>(Apollo Go)", category: "mobility", source: "Baidu", url: "https://apollo.auto/", country: "cn" },
    { id: 506, title: "WeRide<br>(Global L4)", category: "mobility", source: "Smart Mobility", url: "https://www.weride.ai/", country: "cn" },
    { id: 507, title: "Aurora<br>(Autonomous Truck)", category: "mobility", source: "Aurora Tech", url: "https://aurora.tech/", country: "us" },
    { id: 508, title: "Kodiak<br>(Self-Driving Freight)", category: "mobility", source: "Kodiak Robotics", url: "https://kodiak.ai/", country: "us" },
    { id: 509, title: "Einride<br>(Digital Freight)", category: "mobility", source: "Freight Tech", url: "https://www.einride.tech/", country: "se" },
    { id: 510, title: "Gatik<br>(Middle-mile Delivery)", category: "mobility", source: "B2B Logistics", url: "https://gatik.ai/", country: "us" },
    { id: 550, title: "Einride<br>(Autonomous Electric Freight)", category: "mobility", source: "Autonomous Freight", url: "https://www.einride.tech/", country: "se" },
    { id: 1240, title: "Doosan Bobcat<br>(Autonomous & Electric Robotics)", category: "mobility", source: "Unmanned Construction Equipment", url: "www.bobcat.com/kr/ko/", country: "kr" },
    { id: 1220, title: "GoLe Robotics<br>(Smart Construction & Logistics)", category: "mobility", source: "Smart Construction & Logistics", url: "http://golerobotics.com/", country: "kr" },
    { id: 502, title: "Tesla<br>(Autonomous Ecosystem: Cybercab & Optimus)", category: "mobility", source: "The Future of Autonomous Life", url: "https://www.tesla.com/we-robot", country: "us" },
    { id: 106, title: "GAC Group<br>(Intelligent Mobility & Flying Robot)", category: "mobility", source: "GAC", url: "https://www.gac.com.cn/", country: "cn" }, 

    // Marine (Underwater & Subsea Robots) ---
    { id: 6001, title: "WHOI<br>(Alvin & Remus - Deep Sea Exploration)", category: "Marine", source: "Discovered Titanic / Premier Ocean Research", url: "https://www.whoi.edu/what-are-ocean-robots/", country: "us" },
    { id: 6002, title: "Eelume<br>(Snake-like Subsea Robot)", category: "Marine", source: "Autonomous Maintenance for Subsea Infrastructure", url: "https://eelume.com/", country: "no" },
    { id: 6003, title: "QYSEA<br>(FIFISH Underwater Drones)", category: "Marine", source: "Consumer & Industrial Underwater Exploration", url: "https://www.qysea.com/", country: "cn" },
    
    // Medical
    { id: 3001, title: "Intuitive Surgical (Da Vinci)", category: "medical", source: "Intuitive Surgical", url: "https://www.intuitive.com/", country: "us" }, 
    { id: 3002, title: "Stryker (Mako Surgical Robot)", category: "medical", source: "Stryker", url: "https://www.stryker.com/us/en/joint-replacement/systems/Mako_SmartRobotics_Overview.html", country: "us" },
    { id: 3003, title: "Medtronic (Surgical Robotics)", category: "medical", source: "Medtronic", url: "https://www.medtronic.com/us-en/c/surgical-robotics.html", country: "ie" },
    { id: 3004, title: "CMR Surgical (Versius)", category: "medical", source: "CMR Surgical", url: "https://cmrsurgical.com/", country: "gb" },
    { id: 3005, title: "Siemens Healthineers (Corindus)", category: "medical", source: "Siemens", url: "https://www.siemens-healthineers.com/endovascular-robotics", country: "de" },
    { id: 3006, title: "Curexo (ROBODOC, CUVIS)", category: "medical", source: "Curexo", url: "http://www.curexo.com/", country: "kr" }, 
    { id: 3007, title: "Koh Young Technology", category: "medical", source: "Koh Young Technology", url: "https://www.kohyoung.com/", country: "kr" }, 
    { id: 3008, title: "MedinTeq (Endoscopy Robot)", category: "medical", source: "MedinTeq", url: "https://medintech.co.kr/", country: "kr" }, 
    { id: 1106, title: "ReWalk Robotics", category: "medical", sub: "Exoskeleton Rehab", url: "https://rewalk.com/", country: "il" },
    { id: 3051, title: "Zimmer Biomet (ROSA Robotics)", category: "medical", source: "Brain & Knee Surgery", url: "https://www.zimmerbiomet.com/en/products-and-solutions/zb-edge/rosa.html", country: "us" },
    { id: 3052, title: "Smith+Nephew (Cori Surgical System)", category: "medical", source: "Handheld Robotics", url: "https://www.smith-nephew.com/en-us/health-care-professionals/products/orthopaedics/cori", country: "gb" },
    { id: 3053, title: "Ekso Bionics (EksoNR)", category: "medical", source: "Rehabilitation Exoskeleton", url: "https://eksobionics.com/", country: "us" },
    { id: 3054, title: "Hocoma (Lokomat)", category: "medical", source: "Robotic Gait Training", url: "https://www.hocoma.com/", country: "ch" },
    { id: 3055, title: "Vicarious Surgical", category: "medical", source: "Next-gen Abdominal Surgery", url: "https://www.vicarioussurgical.com/", country: "us" },
    { id: 3056, title: "Asensus Surgical (Senhance)", category: "medical", source: "Digital Laparoscopy", url: "https://www.asensus.com/", country: "us" },
    { id: 3057, title: "MicroPort MedBot", category: "medical", source: "Multi-specialty Surgical", url: "https://www.medbot.com.cn/en", country: "cn" },
    { id: 3058, title: "Think Surgical (TMAX)", category: "medical", source: "Orthopedic Surgery", url: "https://thinksurgical.com/", country: "us" },
    { id: 3059, title: "EasyEndo Surgical", category: "medical", source: "Flexible Endoscopic Robot", url: "http://easyendo.com/", country: "kr" },
    { id: 3060, title: "Heimrobot (Elderly Care)", category: "medical", source: "Assistive Care Robot", url: "https://heimrobot.com/", country: "kr" },
    { id: 3061, title: "Bionics (Rehab Robot)", category: "medical", source: "Walking Rehabilitation", url: "http://www.bionicskorea.com/", country: "kr" },
    { id: 1101, title: "URG Life Science (uLab Series)", category: "medical", source: "Lab Automation Robotics", url: "https://unitedrobotics.group/industries/life-science", country: "de" },
    { id: 3013, title: "MEERE COMPANY (Revo-i)", category: "medical", source: "Laparoscopic Surgical Robot", url: "http://revosurgical.com/", country: "kr" },
    { id: 3063, title: "Distalmotion (Dexter)", category: "medical", source: "Hybrid Robotic Surgery", url: "https://distalmotion.com/", country: "ch" },
    { id: 1111, title: "Kinova Medical", category: "medical", source: "Surgical & Assistive Robotics", url: "https://www.kinovarobotics.com/sector/medical-robotics", country: "ca" },
     
    // Farm
    { id: 501, title: "DJI<br>(Agricultural Drones)", category: "farm", source: "DJI", url: "https://ag.dji.com/?backup_page=index&target=en", country: "cn" }, 
    { id: 1420, title: "Blue River Technology<br>(Precision Weeding Robot)", category: "farm", source: "See & Spray™ AI Technology", url: "https://www.bluerivertechnology.com/our-products/", country: "us" },
    { id: 1109, title: "Lely<br>(Dairy Farm Robotics)", category: "farm", sub: "Dairy Farm Robotics", url: "https://www.lely.com/", country: "nl" },
    { id: 503, title: "John Deere<br> (Autonomous Tractor)", category: "farm", source: "John Deere", url: "https://www.deere.com/en/", country: "us" },
    { id: 504, title: "Harvest CROO<br>(Strawberry Picking)", category: "farm", source: "Harvest CROO", url: "https://harvestcroo.com/", country: "us" },
    { id: 505, title: "Carbon Robotics<br>(LaserWeeder)", category: "farm", source: "Carbon Robotics", url: "https://carbonrobotics.com/", country: "us" },
    { id: 506, title: "Naïo Technologies<br>(Weeding Robot)", category: "farm", source: "Naïo Technologies", url: "https://www.naio-technologies.com/en/", country: "fr" },
    { id: 507, title: "Dogtooth<br>(Fruit Picking)", category: "farm", source: "Dogtooth Robotics", url: "https://dogtooth.tech/", country: "gb" },
    { id: 508, title: "BouMatic<br>(Robotic Milking)", category: "farm", source: "BouMatic", url: "https://boumatic.com/", country: "us" },
    { id: 509, title: "Priva<br>(Greenhouse Automation)", category: "farm", source: "Priva", url: "https://www.priva.com/", country: "nl" },
    { id: 1410, title: "Antobot<br>(mobile platform & fruit counting)", category: "farm", source: "Sustainable Precision Farming", url: "https://www.antobot.ai/", country: "gb" },
    { id: 512, title: "Daedong<br>(Autonomous Farming)", category: "farm", source: "AI Agriculture Robot", url: "https://daedong-kioti.com/innovation/futureagriculture/", country: "kr" },
    
    // Logistics
    { id: 1111, title: "Amazon Robotics<br>(Next-Gen Fulfillment & Autonomous AMRs)", category: "logistics", source: "The World's Largest Robotic Warehouse Ecosystem", url: "https://www.aboutamazon.com/news/operations/amazon-robotics-milestones", country: "us" },
    { id: 1108, title: "Locus Robotics<br>(Collaborative Autonomous Mobile Robots for Fulfillment)", category: "logistics", source: "Leader in High-Efficiency Warehouse Automation", url: "https://www.locusrobotics.com/", country: "us" },
    { id: 1114, title: "Zebra Technologies<br>(Fetch Robotics AMRs & Smart Data Solutions)", category: "logistics", source: "Leader in Data-Driven Logistics Automation", url: "https://www.zebra.com/us/en/products/robotics.html", country: "us" },
    { id: 620, title: "Toyota (Autopilot Forklifts)", category: "logistics", source: "Toyota Material Handling", url: "https://www.toyotaforklift.com/", country: "jp" },
    { id: 621, title: "Linde (Automated Forklifts)", category: "logistics", source: "KION Group", url: "https://www.linde-mh.com/en/Solutions/Automation/", country: "de" }, 
    { id: 622, title: "VisionNav (Driverless Forklift)", category: "logistics", source: "VisionNav", url: "https://www.visionnav.com/", country: "cn" },
    { id: 623, title: "Vecna (Autonomous Pallet Handling)", category: "logistics", source: "Vecna Robotics", url: "https://www.vecnarobotics.com/", country: "us" },
    { id: 624, title: "Jungheinrich (Automated Warehouse)", category: "logistics", source: "Jungheinrich", url: "https://www.jungheinrich.com/en/solutions/automation", country: "de" },
    { id: 626, title: "Mobyus (Autonomous Fork Lift)", category: "logistics", source: "Mobyus NVC", url: "http://www.mobyus.com/afl", country: "kr" },
    { id: 627, title: "Balyo (Robotic Forklift Kits)", category: "logistics", source: "Balyo", url: "https://www.balyo.com/", country: "fr" },
    { id: 1110, title: "Hyster-Yale Materials Handling<br>(Autonomous Lift Trucks & Heavy Logistics)", category: "logistics", source: "Global Leader in Heavy-Duty Material Handling", url: "https://www.hyster-yale.com/", country: "us" },
    { id: 1112, title: "Mitsubishi Logisnext<br>(Integrated Autonomous Forklifts & Smart Logistics)", category: "logistics", source: "A Mitsubishi Heavy Industries Group Company", url: "https://www.logisnext.com/en/", country: "jp" },
    { id: 1102, title: "MiR (Mobile Industrial Robots)", category: "logistics", sub: "Industrial AMR", url: "https://www.mobile-industrial-robots.com/", country: "dk" },
    { id: 626, title: "Hyundai Wia (AMR & Parking Robot)", category: "logistics", source: "Autonomous Logistics Solution", url: "https://en.hyundai-wia.com/main/main.asp", country: "kr" },
    { id: 1109, title: "Exotec<br>(3D Skypod Robotic Goods-to-Person System)", category: "logistics", source: "Innovative Vertical Climbing Storage Solutions", url: "https://www.exotec.com/", country: "fr" },
    { id: 1106, title: "Starship Technologies<br>(Autonomous Last-Mile Delivery Robot)", category: "logistics", source: "Global Leader in Sidewalk Delivery Services", url: "https://www.starship.xyz/", country: "us" },
    { id: 1107, title: "Swisslog<br>(Advanced Logistics & Healthcare Automation)", category: "logistics", source: "A KUKA Group Company specializing in ASRS & AI Picking", url: "https://www.swisslog.com/", country: "ch" },
    { id: 1113, title: "Symbotic<br>(AI-Powered End-to-End Warehouse Automation)", category: "logistics", source: "Revolutionizing Supply Chain with Autonomous Robot Fleets", url: "https://www.symbotic.com/", country: "us" },
    { id: 661, title: "Schneider Electric (Industrial AI)", category: "automation", source: "Digital Automation", url: "https://www.se.com/", country: "fr" },
    { id: 1115, title: "KION Group<br>(Linde, STILL & Dematic Automation Solutions)", category: "logistics", source: "Global Leader in Smart Supply Chain & Industrial Trucks", url: "https://www.kiongroup.com/en/", country: "de" },
    { id: 1104, title: "OTTO Motors<br>(Material Handling AMRs)", category: "logistics", source: "A Rockwell Automation Company", url: "https://ottomotors.com/", country: "ca" },
    { id: 1116, title: "Serve Robotics<br>(AI-Powered Sidewalk Delivery)", category: "logistics", source: "Uber Spinoff Leading Last-Mile Autonomy", url: "https://www.serverobotics.com/", country: "us" },
    { id: 1120, title: "Geek+<br>(Goods-to-Person AMR Solutions)", category: "logistics", source: "World's #1 AMR Market Share", url: "https://www.geekplus.com/", country: "cn" },
    { id: 1121, title: "AutoStore<br>(Cube Storage Automation)", category: "logistics", source: "High-Density Warehouse Robotics", url: "https://www.autostoresystem.com/", country: "no" },
    { id: 1122, title: "Zipline<br>(Autonomous Drone Delivery)", category: "logistics", source: "Life-Saving Medical Delivery Drone", url: "https://www.zipline.com/", country: "us" },
    { id: 1123, title: "Wing<br>(Alphabet Drone Delivery)", category: "logistics", source: "Google's Drone Delivery Service", url: "https://wing.com/", country: "us" },
    
    // Wearables
    { id: 1201, title: "Cyberdyne<br>(HAL Hybrid Assistive Limb)", category: "wearable", source: "Pioneer in Cybernic Technology", url: "https://www.cyberdyne.jp/english/", country: "jp" },
    { id: 1202, title: "German Bionic<br>(Smart Industrial Exoskeleton)", category: "wearable", source: "AI-Powered Lumbar Support for Workers", url: "https://www.germanbionic.com/", country: "de" },
    { id: 1203, title: "Ekso Bionics<br>(Medical & Industrial Exoskeletons)", category: "wearable", source: "Leader in Human Augmentation", url: "https://eksobionics.com/", country: "us" },
    { id: 1204, title: "Lifeward (ReWalk)<br>(Personal Mobility Exoskeleton)", category: "wearable", source: "Empowering People with Mobility Impairment", url: "https://www.lifeward.com/", country: "us" },
    { id: 1103, title: "Comau MATE<br>(Upper-limb Work Support)", category: "wearable", source: "Ergonomic Industrial Wearable", url: "https://www.comau.com/en/competencies/robotics/wearable-robotics/", country: "it" },
    { id: 1205, title: "Hyundai Rotem<br>(X-ble Wearable Robot Series)", category: "wearable", source: "Industrial & Medical Muscle Support", url: "https://www.hyundai-rotem.co.kr/Business/Robot/Business_Intro.asp", country: "kr" },
    { id: 1206, title: "SuitX (Ottobock)<br>(Industrial Power Assist Exoskeleton)", category: "wearable", source: "Leader in Workplace Ergonomics", url: "https://www.suitx.com/", country: "de" },
    { id: 1207, title: "Marsi Bionics<br>(Pediatric Gait Exoskeleton)", category: "wearable", source: "World's First Robot for Children with SMA", url: "https://www.marsibionics.com/", country: "es" },
    { id: 1208, title: "Hexar Humancare<br>(Knee & Lumbar Support System)", category: "wearable", source: "Precision Rehabilitation Technology", url: "http://hexarhc.com/", country: "kr" },
    { id: 1209, title: "Hilti (EXO-O1)<br>(Construction Wearable Robot)", category: "wearable", source: "Overhead Task Muscle Relief", url: "https://www.hilti.com/c/CLS_EXOSKELETONS", country: "li" },
    { id: 1210, title: "WIRobotics<br>(WIM Everyday Mobility Gear)", category: "wearable", source: "Ultra-Lightweight Walk Assist", url: "https://wirobotics.com/", country: "kr" },
    { id: 1211, title: "Bionik Labs<br>(InMotion Rehabilitation Robot)", category: "wearable", source: "AI-Driven Neuro-Recovery Solution", url: "https://www.bioniklabs.com/", country: "ca" },
    { id: 1201, title: "Cyberdyne<br>(HAL Hybrid Assistive Limb)", category: "wearable", source: "Pioneer in Cybernic Technology", url: "https://www.cyberdyne.jp/english/", country: "jp" },
    { id: 1202, title: "German Bionic<br>(Smart Industrial Exoskeleton)", category: "wearable", source: "AI-Powered Lumbar Support for Workers", url: "https://www.germanbionic.com/", country: "de" },
    { id: 1203, title: "Ekso Bionics<br>(Medical & Industrial Exoskeletons)", category: "wearable", source: "Leader in Human Augmentation", url: "https://eksobionics.com/", country: "us" },
    { id: 1205, title: "Hyundai Rotem<br>(X-ble Wearable Robot Series)", category: "wearable", source: "Industrial & Medical Muscle Support", url: "https://www.hyundai-rotem.co.kr/Business/Robot/Business_Intro.asp", country: "kr" },
    { id: 1212, title: "Wandercraft<br>(Atalante Self-Balancing Exoskeleton)", category: "wearable", source: "Hands-free Rehabilitation Robot", url: "https://www.wandercraft.eu/", country: "fr" },
    { id: 1213, title: "Innophys<br>(Every Muscle Suit)", category: "wearable", source: "Electricity-free Pneumatic Support", url: "https://innophys.jp/en/", country: "jp" },
    { id: 1214, title: "Roam Robotics<br>(Forge Soft Exoskeleton)", category: "wearable", source: "Pneumatic Knee & Mobility Support", url: "https://www.roamrobotics.com/", country: "us" },
    { id: 1215, title: "Trexo Robotics<br>(Pediatric Wearable Exoskeleton)", category: "Wearable", source: "Robotic Legs for Children with Disabilities", url: "https://trexorobotics.com/", country: "ca" },
    { id: 1217, title: "Angel Robotics<br>(Wearable Suits for Rehab & Industry)", category: "Wearable", source: "Cybathlon Gold Medalist & KAIST Spin-off", url: "https://angel-robotics.com/en/", country: "kr" },
    
    // Home & BLDG 
    { id: 1450, title: "DEEP Robotics<br>(Industrial All-Terrain Inspection Robot)", category: "Home & BLDG", source: "Pioneering Embodied AI Technology", url: "https://www.deeprobotics.cn/en/", country: "cn"},
    { id: 1001, title: "Amazon<br>(Astro Home Robot)", category: "Home & BLDG", source: "Amazon", url: "https://www.aboutamazon.com/news/devices/meet-astro-a-home-robot-unlike-any-other", country: "us" }, 
    { id: 1002, title: "iRobot<br>(Roomba & Braava)", category: "Home & BLDG", source: "iRobot", url: "https://www.irobot.com/", country: "us" }, 
    { id: 1003, title: "Sony<br>(aibo Robotic Companion)", category: "Home & BLDG", source: "Sony", url: "https://us.aibo.com/", country: "jp" }, 
    { id: 1004, title: "Dreame Technology<br>(Window Cleaning Robot)", category: "Home & BLDG", source: "Smart Cleaning", url: "https://global.dreametech.com/", country: "cn" },
    { id: 1005, title: "Ecovacs Robotics<br>(Intelligent Home Service)", category: "Home & BLDG", source: "Service Robots", url: "https://www.ecovacs.com/", country: "cn" },
    { id: 1006, title: "Enabot (EBO)<br>(Family robot)", category: "Home & BLDG", source: "Companion Robot", url: "https://www.enabot.com/", country: "cn" },
    { id: 1007, title: "Labrador Systems<br>(Assistive Robot)", category: "Home & BLDG", source: "Assistive Robot", url: "https://labradorsystems.com/", country: "us" },
    { id: 1008, title: "LIVING.AI<br>(EMO & AIBI Desktop Pet)", category: "Home & BLDG", source: "AI Desktop Pet", url: "https://living.ai/", country: "cn" },
    { id: 1009, title: "Moxie Robot<br>(AI Social Companion)", category: "Home & BLDG", source: "Learning Robot", url: "https://embodied.com/", country: "us" },
    { id: 1010, title: "Narwal Robotics<br>(All for Clean Home)", category: "Home & BLDG", source: "Cleaning Robot", url: "https://shop.narwal.com/", country: "cn" },
    { id: 1011, title: "Roborock<br>(Robotic Vacuum Cleaner)", category: "Home & BLDG", source: "Smart Home", url: "https://global.roborock.com/", country: "cn" },
    { id: 1012, title: "Samsung Ballie<br>(Robot companion)", category: "Home & BLDG", source: "Samsung", url: "https://news.samsung.com/us/samsung-ballie-ai-companion-robot-home-video-ces-2024", country: "kr" },
    { id: 1107, title: "Intuition Robotics<br>(AI care companion robot)", category: "Home & BLDG", sub: "Social Companion AI", url: "https://www.intuitionrobotics.com/", country: "il" },
    { id: 1140, title: "Aiper<br>(Cordless Pool Cleaner)", category: "Home & BLDG", source: "Cordless Pool Cleaner", url: "https://aiper.com/", country: "us" },
    { id: 1150, title: "Tombot<br>(Jennie emotional support)", category: "Home & BLDG", source: "Emotional Support Robot Dog", url: "https://www.tombot.com/", country: "us" },
    { id: 1190, title: "Sentigent<br>(Rover X3 Outdoor Companion Robot)", category: "Home & BLDG", source: "Outdoor Companion Robot", url: "https://www.sentigent.com/", country: "cn" },
    { id: 1200, title: "SwitchBot Onero H1<br>(Multitasking Housebot)", category: "Home & BLDG", source: "AI Multitasking Housebot", url: "https://www.switch-bot.com/pages/onero-h1", country: "cn" },
    { id: 1301, title: "Husqvarna Automower<br>(Robot Lawn mowers)", category: "Home & BLDG", source: "Robotic Lawn Mower", url: "https://www.husqvarna.com/us/robotic-lawn-mowers/", country: "se" },
    { id: 1303, title: "Mammotion<br>(Lawn Mower)", category: "Home & BLDG", source: "Wire-free Lawn Robot", url: "https://mammotion.com/", country: "cn" },
    { id: 1310, title: "Dyson 360 Vis Nav<br>(robot vacuum)", category: "Home & BLDG", source: "Dyson", url: "https://www.dyson.com/vacuum-cleaners/robot/360-vis-nav", country: "uk" },
    { id: 1311, title: "SharkNinja (Shark AI Robot)", category: "Home & BLDG", source: "Smart Cleaning", url: "https://www.sharkclean.com/robot-vacuums/", country: "us" },
    { id: 1312, title: "eufy Clean<br>(Robot Vacuum>", category: "Home & BLDG", source: "Smart Cleaning", url: "https://www.eufy.com/", country: "cn" },
    { id: 1320, title: "HOBOT Technology<br>(Window Cleaning Robot)", category: "Home & BLDG", source: "Window Cleaning Robot", url: "https://www.hobot.com.tw/", country: "tw" },
    { id: 1330, title: "KEYi Robot<br>(Loona & ClicBot)", category: "Home & BLDG", source: "Smart Petbot", url: "https://keyirobot.com/", country: "cn" },
    { id: 1331, title: "Vector 2.0<br>(Home Robot)", category: "Home & BLDG", source: "AI Companion", url: "https://anki.bot/", country: "us" },
    { id: 1350, title: "Maytronics Dolphin<br>(Robotic Pool Cleaner)", category: "Home & BLDG", source: "Robotic Pool Cleaner", url: "https://maytronics.com/", country: "il" }, // Aiper 외의 메이저 수영장 청소 로봇
    { id: 1351, title: "Grillbot<br>(Automatic Grill Cleaner)", category: "Home & BLDG", source: "Automatic Grill Cleaner", url: "https://grillbots.com/", country: "us" },
    { id: 1353, title: "Matic Robots<br>(Next-Gen Floor Cleaner)", category: "Home & BLDG", source: "Next-Gen Floor Cleaner", url: "https://maticrobots.com/", country: "us" }, // 완전 자율 주행을 강조하는 신생 업체
    { id: 1390, title: "Gausium<br>(Building Service)", category: "Home & BLDG", source: "Commercial Floor Scrubber", url: "https://www.gausium.com/", country: "cn" },
    { id: 1391, title: "Skyline Robotics<br>(OZMO Window Cleaner)", category: "Home & BLDG", source: "High-rise Window Cleaning", url: "https://skylinerobotics.com/", country: "us" },
    { id: 1392, title: "Avidbots<br>(Neo Floor Scrubber)", category: "Home & BLDG", source: "Commercial Facility Cleaning", url: "https://www.avidbots.com/", country: "ca" },
    { id: 1400, title: "Knightscope<br>(Security Robot)", category: "Home & BLDG", source: "24/7 Building Surveillance", url: "https://www.knightscope.com/", country: "us" },
    { id: 4002, title: "LG Electronics<br>(Smart Home AI Agent)", category: "Service", source: "Two-Legged Mobile Smart Home Hub", url: "https://www.lgnewsroom.com/2023/12/lg-to-unveil-smart-home-ai-agent-at-ces-2024/", country: "kr" },

    // AI
    { id: 801, title: "OpenAI (ChatGPT)", category: "ai", source: "OpenAI", url: "https://openai.com/", country: "us" }, 
    { id: 802, title: "Google DeepMind", category: "ai", source: "Google", url: "https://deepmind.google/", country: "gb" }, 
    { id: 803, title: "Anthropic (Claude)", category: "ai", source: "Anthropic", url: "https://www.anthropic.com/", country: "us" }, 
    { id: 804, title: "Meta AI (Llama)", category: "ai", source: "Meta", url: "https://ai.meta.com/", country: "us" },
    { id: 805, title: "Hugging Face (AI Model's Hub)", category: "ai", source: "Hugging Face", url: "https://huggingface.co/", country: "us" },
    { id: 806, title: "Gemini (Google DeepMind)", category: "ai", source: "Google DeepMind", url: "https://gemini.google.com/", country: "us" },
    { id: 1105, title: "ZenRobotics", category: "ai", sub: "AI Waste Sorting", url: "https://zenrobotics.com/", country: "fi" },
    { id: 720, title: "Scale AI", category: "ai", source: "Data Infrastructure", url: "https://scale.com/", country: "us" },
    { id: 807, title: "Mistral AI", category: "ai", source: "Frontier AI Models (France)", url: "https://mistral.ai/", country: "fr" },
    
    // Software
    { id: 701, title: "ROS (Robot Operating System)", category: "software", source: "Open Source", url: "https://www.ros.org/", country: "us" }, 
    { id: 702, title: "NVIDIA Isaac Sim", category: "software", source: "NVIDIA", url: "https://developer.nvidia.com/isaac-sim", country: "us" }, 
    { id: 703, title: "MATLAB & Simulink", category: "software", source: "MathWorks", url: "https://www.mathworks.com/solutions/robotics.html", country: "us" },
    { id: 704, title: "Gazebo Simulator", category: "software", source: "Open Source Robotics", url: "https://gazebosim.org/", country: "us" },
    { id: 705, title: "Intrinsic (Alphabet)", category: "software", source: "Google Subsidiary", url: "https://www.intrinsic.ai/", country: "us" },
    { id: 706, title: "Brain Corp (BrainOS)", category: "software", source: "Autonomous AI", url: "https://www.braincorp.com/", country: "us" },
    { id: 707, title: "Clobot (Robot Control)", category: "software", source: "Korea S/W Leader", url: "https://www.clobot.co.kr/", country: "kr" },
    { id: 708, title: "RobotStudio", category: "software", source: "ABB Robotics", url: "https://new.abb.com/products/robotics/robotstudio", country: "ch" },
    { id: 709, title: "SolidWorks (Robot Design)", category: "software", source: "Dassault Systèmes", url: "https://www.solidworks.com/", country: "fr" },
    { id: 711, title: "Formant (Cloud Robotics)", category: "software", source: "Robot Management", url: "https://formant.io/", country: "us" },
    { id: 712, title: "CloudMinds (HARIX OS)", category: "software", source: "Cloud Robot Pioneer", url: "https://www.cloudminds.com/", country: "cn" },
    { id: 713, title: "Clobot (CROMS)", category: "software", source: "Korea Fleet Management", url: "https://www.clobot.co.kr/", country: "kr" },
    { id: 714, title: "Orbit (Fleet Software)", category: "software", source: "Boston Dynamics", url: "https://bostondynamics.com/products/orbit/", country: "us" },
    { id: 715, title: "Karelics (Fleet Management)", category: "software", source: "Construction Robotics", url: "https://karelics.fi/", country: "fi" },
    { id: 716, title: "MyRobot.cloud", category: "software", source: "Rocketfarm", url: "https://myrobot.cloud/", country: "no" },
    { id: 717, title: "Applied Intuition", category: "software", source: "Autonomous Vehicle Simulation", url: "https://www.appliedintuition.com/", country: "us" },
    { id: 718, title: "Weights & Biases (W&B)", category: "software", source: "AI Developer Platform", url: "https://wandb.ai/", country: "us" },
    
    // Components
    { id: 901, title: "Lidar by Velodyne", category: "components", source: "Velodyne", url: "https://velodynelidar.com/", country: "us" }, 
    { id: 902, title: "Robot Grippers by Robotiq", category: "components", source: "Robotiq", url: "https://robotiq.com/", country: "ca" },
    { id: 903, title: "maxon (Precision Motors)", category: "components", source: "maxon", url: "https://www.maxongroup.com/", country: "ch" },
    { id: 904, title: "Harmonic Drive", category: "components", source: "Harmonic Drive", url: "https://www.harmonicdrive.net/", country: "us" },
    { id: 905, title: "Cognex (Machine Vision)", category: "components", source: "Cognex", url: "https://www.cognex.com/", country: "us" },
    { id: 906, title: "Festo (Automation)", category: "components", source: "Festo", url: "https://www.festo.com/", country: "de" },
    { id: 907, title: "Universal Robots+ (Tools)", category: "components", source: "Universal Robots", url: "https://www.universal-robots.com/plus/", country: "dk" },
    { id: 908, title: "TE Connectivity (Sensors)", category: "components", source: "TE Connectivity", url: "https://www.te.com/", country: "ch" },
    { id: 910, title: "Harmonic Drive - Precision", category: "components", source: "Global Leader", url: "https://www.harmonicdrive.net/", country: "jp" },
    { id: 911, title: "Nabtesco - RV Reducers", category: "components", source: "Global Leader", url: "https://www.nabtesco.com/", country: "jp" },
    { id: 912, title: "ROBOTIS - Dynamixel", category: "components", source: "Korea Specialty", url: "https://www.robotis.com/", country: "kr" },
    { id: 913, title: "SBB Tech - Harmonic Reducers", category: "components", source: "Korea Specialty", url: "http://www.sbb.co.kr/", country: "kr" },
    { id: 914, title: "Maxon Motor - Precision Drives", category: "components", source: "Global Specialty", url: "https://www.maxongroup.com/", country: "ch" }, 
    { id: 915, title: "SPG<br>(High-Precision Robot Reducer & Motor)", category: "components", source: "Korea Specialty", url: "http://www.spg.co.kr/", country: "kr" },
    { id: 950, title: "Velodyne Lidar", category: "components", source: "LiDAR Sensors", url: "https://velodynelidar.com/", country: "us" },
    { id: 951, title: "Ouster<br>(Digital LiDAR Sensor Solutions)", category: "components", source: "Digital LiDAR", url: "https://www.ouster.com/", country: "us" },
    { id: 952, title: "LG Energy Solution", category: "components", source: "Robot Batteries", url: "https://www.lgensol.com/", country: "kr" },
    { id: 953, title: "SOS LAB<br>(High-Performance LiDAR Sensor)", category: "components", source: "Solid-state LiDAR", url: "https://www.soslab.co/en/", country: "kr" },
    { id: 954, title: "Hesai Technology", category: "components", source: "LiDAR Solutions", url: "https://www.hesaitech.com/", country: "cn" },
    { id: 955, title: "HL Mando", category: "components", source: "Radar, Camera & By-Wire Tech", url: "https://www.hlmando.com/en/solution/autonomous-driving.do", country: "kr" },
    { id: 916, title: "Aidin Robotics<br>(Force/Torque Sensor)", category: "components", source: "Physical Interaction Intelligence", url: "https://www.aidinrobotics.co.kr/", country: "kr" },

    // Research
    { id: 30001, title: "Carnegie Mellon Robotics Institute", category: "Research", sub: "AI & Autonomy", url: "https://www.ri.cmu.edu/", country: "us" },
    { id: 30002, title: "MIT CSAIL Robotics", category: "Research", sub: "Robot Learning", url: "https://www.csail.mit.edu/research/robotics", country: "us" },
    { id: 30003, title: "Stanford Robotics Lab", category: "Research", sub: "Vision & HRI", url: "https://robotics.stanford.edu/", country: "us" },
    { id: 30004, title: "Harvard Biodesign Lab", category: "Research", sub: "Soft Robotics", url: "https://biodesign.seas.harvard.edu/", country: "us" },
    { id: 30005, title: "UC Berkeley Robotics (BAIR)", category: "Research", sub: "Biomimetics", url: "https://bair.berkeley.edu/", country: "us" },
    { id: 30006, title: "ETH Zurich Robotics Systems Lab", category: "Research", sub: "System Design", url: "https://rsl.ethz.ch/", country: "ch" },
    { id: 30007, title: "EPFL Biorobotics Laboratory", category: "Research", sub: "Bio-inspired", url: "https://www.epfl.ch/labs/biorob/", country: "ch" },
    { id: 30008, title: "TUM Munich Robotics", category: "Research", sub: "Cognitive Robots", url: "https://www.mirmi.tum.de/", country: "de" },
    { id: 30009, title: "Imperial College Robotics", category: "Research", sub: "Surgical & Space", url: "https://www.imperial.ac.uk/robotics/", country: "gb" },
    { id: 30010, title: "University of Tokyo Robotics", category: "Research", sub: "Human-Centered", url: "https://www.u-tokyo.ac.jp/en/research/robotics.html", country: "jp" },
    { id: 30011, title: "KAIST Robotics Program", category: "Research", sub: "Humanoid & Field", url: "https://robotics.kaist.ac.kr/", country: "kr" },
    { id: 30013, title: "IIT (Italian Institute of Tech)", category: "Research", sub: "Advanced Humanoid", url: "https://www.iit.it/research/robotics", country: "it" },
    { id: 30015, title: "University of Michigan Robotics", category: "Research", sub: "Legged Locomotion", url: "https://robotics.umich.edu/", country: "us" },
    { id: 30016, title: "University of Sydney Robotics", category: "Research", sub: "Field Robotics", url: "https://www.sydney.edu.au/engineering/our-research/robotics.html", country: "au" },
    { id: 30023, title: "Tsinghua University (Intelligent Systems)", category: "Research", sub: "AI & Manufacturing", url: "https://www.tsinghua.edu.cn/en/Research/Research_Centers.htm", country: "cn" },
    { id: 30024, title: "Shanghai Jiao Tong University (Robotics)", category: "Research", sub: "Integrated Systems", url: "http://robotics.sjtu.edu.cn/", country: "cn" },
    { id: 30025, title: "Harbin Institute of Technology (HIT)", category: "Research", sub: "Space & Industrial", url: "http://en.hit.edu.cn/about/research_centers", country: "cn" },
    { id: 30026, title: "CAS - Shenyang Institute of Automation", category: "Research", sub: "National Robot Base", url: "http://english.sia.cas.cn/", country: "cn" },
    { id: 30027, title: "Zhejiang University (Robotics Lab)", category: "Research", sub: "Intelligent Control", url: "https://www.zju.edu.cn/english/research/index.html", country: "cn" },
    { id: 30090, title: "Peking Univ. School of Intelligence", category: "Research", sub: "Robotics & AI Research", url: "https://sai.pku.edu.cn/znxyenglish/Research_Area/Reseach_Themes.htm", country: "cn" },
    { id: 30030, title: "Seoul National University (Robotics Lab)", category: "Research", sub: "Dynamics & Soft Robotics", url: "http://robotics.snu.ac.kr/", country: "kr" },
    { id: 30031, title: "KIST Intelligence and Interaction", category: "Research", sub: "Social & Assistive Robots", url: "https://ir.kist.re.kr/", country: "kr" },
    { id: 30032, title: "Hanyang University (Robot Engineering)", category: "Research", sub: "Industrial & Service", url: "https://robot.hanyang.ac.kr/", country: "kr" },
    { id: 30033, title: "ETRI (Robot & AI Research)", category: "Research", sub: "Intelligence SW & OS", url: "https://www.etri.re.kr/kor/main/main.etri", country: "kr" },
    { id: 30034, title: "Korea University (Intelligent Robotics)", category: "Research", sub: "Machine Learning & HRI", url: "https://isr.korea.ac.kr/", country: "kr" },
    { id: 30035, title: "POSTECH Robotics Lab", category: "Research", sub: "Industrial AI", url: "https://robotics.postech.ac.kr/", country: "kr" },
    { id: 30050, title: "NTU Singapore (ROSE)", category: "Research", sub: "Service & AI", url: "https://www.ntu.edu.sg/rose", country: "sg" },
    { id: 30060, title: "University of Oxford (Oxford Robotics Institute)", category: "Research", sub: "Mobile & Field Robotics", url: "https://ori.ox.ac.uk/", country: "gb" },
    { id: 30063, title: "Delft University of Technology (TU Delft)", category: "Research", sub: "Cognitive Robotics", url: "https://www.tudelft.nl/en/ai/robotics", country: "nl" },
    { id: 30064, title: "Georgia Institute of Technology (Georgia Tech)", category: "Research", sub: "Institute for Robotics", url: "https://robotics.gatech.edu/", country: "us" },
    { id: 3020, title: "Johns Hopkins LCSR<br>(Computational Sensing & Medical Robotics)", category: "Research", source: "Global Leader in Surgical & Healthcare Robotics", url: "https://lcsr.jhu.edu/", country: "us" },
    { id: 30071, title: "Wyss Institute (Harvard)", category: "Research", sub: "Soft Medical Robotics", url: "https://wyss.harvard.edu/", country: "us" },
    { id: 30072, title: "Hamlyn Centre (Imperial)", category: "Research", sub: "Robotic Surgery", url: "https://www.imperial.ac.uk/hamlyn-centre/", country: "gb" },
    { id: 3015, title: "RoMeLa (UCLA)<br>(Creative Robotics & Mechanisms Lab)", category: "Research", source: "Led by Prof. Dennis Hong", url: "https://www.romela.org/", country: "us" },
    { id: 3016, title: "Clearpath Robotics<br>(Autonomous R&D Platforms)", category: "research", source: "Standard for ROS-Based UGV Systems", url: "https://clearpathrobotics.com/", country: "ca" },
    { id: 3017, title: "Google DeepMind<br>(Robotic Transformers & Embodied AI)", category: "research", source: "Pioneer in Robotic Intelligence Models", url: "https://deepmind.google/blog/shaping-the-future-of-advanced-robotics/", country: "gb" },
    
     // Events
    { id: 10001, title: "ROBOT WORLD", category: "events", source: "KINTEX/KIRIA", url: "https://www.robotworld.or.kr/", country: "kr" }, 
    { id: 10002, title: "iREX (Int'l Robot Exhibition)", category: "events", source: "JARA/NEDO", url: "https://irex.nikkan.co.jp", country: "jp" },
    { id: 10003, title: "automatica Munich", category: "events", source: "Messe München", url: "https://automatica-munich.com/", country: "de" }, 
    { id: 10004, title: "IEEE RAS (ICRA 2025)", category: "events", source: "IEEE", url: "https://2025.ieee-icra.org/", country: "us" }, 
    { id: 10005, title: "AI EXPO KOREA", category: "events", source: "AI EXPO", url: "https://www.aiexpo.co.kr/", country: "kr" },
    { id: 10006, title: "DJI Robotics (RoboMaster)", category: "events", source: "DJI", url: "https://www.robomaster.com/en-US", country: "cn" },
    { id: 10007, title: "World Robot Conference (WRC)", category: "events", sub: "Global Robot Summit", url: "http://www.worldrobotconference.com/en/", country: "cn" },
    { id: 10009, title: "CES", category: "events", sub: "Consumer Tech & AI", url: "https://www.ces.tech", country: "us" },
    { id: 10010, title: "Hannover Messe", category: "events", sub: "Integrated Industry", url: "https://www.hannovermesse.de/en/", country: "de" },
    { id: 10011, title: "RoboCup World Championship", category: "events", sub: "AI & Robot Competition", url: "https://www.robocup.org/", country: "un" },
    { id: 10012, title: "NVIDIA GTC (Robotics)", category: "events", sub: "Developer Conference", url: "https://www.nvidia.com/gtc/", country: "us" },
    { id: 10013, title: "The Logistics World (Mexico)", category: "events", sub: "Logistics & Supply Chain", url: "https://thelogisticsworld.com/expo/", country: "mx" },
    { id: 10014, title: "Modex Show", category: "events", sub: "Supply Chain Solutions", url: "https://www.modexshow.com/", country: "us" },
    { id: 10015, title: "Automate Show (Chicago 2026)", category: "events", source: "A3 (Association for Advancing Automation)", url: "https://www.automateshow.com/", country: "us" },

    // Organization 
    { id: 20001, title: "IFR<br>(International Federation of Robotics)", category: "organization", source: "IFR", url: "https://ifr.org/", country: "de" }, 
    { id: 20003, title: "Silicon Valley Robotics", category: "organization", source: "SVR", url: "https://www.svrobo.org/", country: "us" },
    { id: 20002, title: "IEEE ICRA 2025<br>(Robotics & Automation Conference)", category: "organization", source: "IEEE", url: "https://2025.ieee-icra.org/", country: "us" }, 
    { id: 20004, title: "ISO TC 299 (Robotics)", category: "organization", source: "ISO", url: "https://committee.iso.org/home/tc299", country: "ch" },
    { id: 20005, title: "KIRIA (Robot Industry Promotion)", category: "organization", sub: "Gov Agency / Promotion", url: "https://www.kiria.org/", country: "kr" },
    { id: 20006, title: "KAR (Korea Robot Industry Association)", category: "organization", sub: "Trade Association", url: "http://www.korearobot.or.kr/", country: "kr" },
    { id: 20007, title: "A3<br>(Association for Advancing Automation)", category: "organization", sub: "North America Trade Group", url: "https://www.automate.org/", country: "us" },
    { id: 20008, title: "JARA (Japan Robot Association)", category: "organization", sub: "Japan Industry Body", url: "https://www.jara.jp/english/", country: "jp" },
    { id: 20009, title: "VDMA Robotics + Automation", category: "organization", sub: "European Industry Standards", url: "https://www.vdma.org/robotics-automation", country: "de" },
    { id: 20010, title: "TAIROA (Taiwan Robot Association)", category: "organization", sub: "Automation & Intelligence", url: "https://www.tairoa.org.tw/", country: "tw" },
    { id: 20011, title: "CRIA (China Robot Industry Alliance)", category: "organization", sub: "China Strategic Alliance", url: "http://cria.mei.net.cn/", country: "cn" }, 
    { id: 20012, title: "MassRobotics", category: "organization", sub: "Robotics Innovation Hub", url: "https://www.massrobotics.org/", country: "us" },
    { id: 20021, title: "CRIA (China Robot Industry Alliance)", category: "organization", sub: "China National Body", url: "http://cria.mei.net.cn/", country: "cn" },
    { id: 20022, title: "BARA (British Automation & Robot Association)", category: "organization", sub: "UK Industry Body", url: "https://www.bara.org.uk/", country: "gb" },
    { id: 20023, title: "SIRI (Italian Association of Robotics)", category: "organization", sub: "Italy National Association", url: "https://www.ss-siri.it/", country: "it" },
   
    //Educational
    { id: 50001, title: "UNESCO STEM Education", category: "Educational", source: "UNESCO", url: "https://www.unesco.org/en/stem", country: "un" },
    { id: 50002, title: "ISTE (EdTech Standards)", category: "Educational", source: "ISTE", url: "https://www.iste.org/", country: "us" },
    { id: 50101, title: "FIRST Robotics (K-12)", category: "Educational", source: "FIRST", url: "https://www.firstinspires.org/", country: "us" },
    { id: 50102, title: "Code.org (Computer Science)", category: "Educational", source: "Code.org", url: "https://code.org/", country: "us" },
    { id: 50103, title: "Khan Academy (STEM Courses)", category: "Educational", source: "Khan Academy", url: "https://www.khanacademy.org/", country: "us" },
    { id: 50104, title: "Girls Who Code", category: "Educational", source: "Non-profit", url: "https://girlswhocode.com/", country: "us" },
    { id: 50105, title: "Scratch Foundation", category: "Educational", source: "MIT Media Lab", url: "https://scratch.mit.edu/", country: "us" },
    { id: 50106, title: "MIND Research Institute", category: "Educational", source: "ST Math", url: "https://www.mindresearch.org/", country: "us" },
    { id: 50201, title: "NASA STEM Engagement", category: "Educational", source: "NASA", url: "https://www.nasa.gov/learning-resources/", country: "us" },
    { id: 50202, title: "NSF STEM Education (EDU)", category: "Educational", source: "National Science Foundation", url: "https://new.nsf.gov/edu", country: "us" },
    { id: 50203, title: "Smithsonian Science Center", category: "Educational", source: "Smithsonian", url: "https://ssec.si.edu/", country: "us" },
    { id: 50204, title: "DoD STEM (Defense Dept)", category: "Educational", source: "U.S. Dept of Defense", url: "https://www.dodstem.us/", country: "us" },
    { id: 50301, title: "Project Lead The Way (PLTW)", category: "Educational", source: "STEM Curriculum", url: "https://www.pltw.org/", country: "us" },
    { id: 50302, title: "STEM.org<br>(Global STEM Research & Accreditation)", category: "Educational", source: "Research Org", url: "https://stem.org/", country: "us" },
    { id: 1341, title: "Sphero<br>(Coding & STEM Robots)", category: "Educational", source: "Coding & STEM Robots", url: "https://sphero.com/", country: "us" },
];